In [1]:
from sklearn import datasets

In [2]:
iris = datasets.load_iris()

## Scikit-learn ile veri onisleme
1. numerik verilerin olceklendirilmesi(normalizasyon,standardizasyon,kesikli hale getirme()
2. Ordinal verilerin kodlanmasi
3. Nominal verilerin yeniden kodlanmasi(encode)


In [5]:
# 1- numerik verilerin olceklendirilmesi
from sklearn.preprocessing import MinMaxScaler

In [6]:
MinMaxScaler?

where min,max=feature_range

In [ ]:
mm_scaler =MinMaxScaler(feature_range = (0,1))

scikitlearn onemli fonksiyonlar
- fit()
- transform()
- fit_transform()
- inverse_transform()

In [ ]:
mm_scaler.fit_transform(dataname)

In [ ]:
import sklearn.preprocessing import MaxAbsScaler

In [ ]:
mas_scaler =MaxAbsScaler()

In [ ]:
mas_scaler.fit_transform(dataname)

In [ ]:
from sklearn.preprocessing import Normalizer

In [ ]:
normalizer.fit_transform(dataname)

In [ ]:

# 2- Ordinal verilerin kodlanmasi
import sklearn.preprocessing  import OrdinalEncoder


In [ ]:
encoder =OrdinalEncoder(dataname)

In [ ]:
## sutun sayisini bire cevirinnumpy)

In [ ]:
# Dakika 54... takilinca don 2020 dersi

encoder.fit_transform(name.values.reshape(-1,1))

## Nominal verilerin encode edilmesi
1. scitlearn icerisinde onehotencoding() fonksiyonu ile yapilir.

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
OneHatEncoder?

In [ ]:
onehot=OneHotEncoder()

In [ ]:
Onehot.fit_transform(name).toarray()


## Eksik veriyi degistirmek

## Mustafa Veri Standardizasyonu- Donusumu

### Standartlastirma

In [7]:
import numpy as np
import pandas as pd

In [8]:
V1 = np.array([1,3,6,5,7])
V2 = np.array([7,7,5,8,12])
V3 = np.array([6,12,5,6,14])

In [10]:
df=pd.DataFrame({
    "V1":V1,
    'V2':V2,
    'V3':V3
})
df=df.astype(float)
df

V1    V2    V3
0  1.0   7.0   6.0
1  3.0   7.0  12.0
2  6.0   5.0   5.0
3  5.0   8.0   6.0
4  7.0  12.0  14.0

In [11]:
from sklearn import  preprocessing


In [12]:
##standart sapma 1,ortalama 0 
# degistirmeler anayapimizi degistirmiyor
preprocessing.scale(df)

array([[-1.57841037, -0.34554737, -0.70920814],
       [-0.64993368, -0.34554737,  0.92742603],
       [ 0.74278135, -1.2094158 , -0.98198051],
       [ 0.27854301,  0.08638684, -0.70920814],
       [ 1.2070197 ,  1.81412369,  1.47297076]])

In [13]:
df

V1    V2    V3
0  1.0   7.0   6.0
1  3.0   7.0  12.0
2  6.0   5.0   5.0
3  5.0   8.0   6.0
4  7.0  12.0  14.0

### Normalization

In [ ]:
# bir degiskenini degerinin 0-1 araligina donusturmek

In [14]:
preprocessing.normalize(df)

array([[0.10783277, 0.75482941, 0.64699664],
       [0.21107926, 0.49251828, 0.84431705],
       [0.64699664, 0.53916387, 0.53916387],
       [0.4472136 , 0.71554175, 0.53665631],
       [0.35491409, 0.60842415, 0.70982818]])

## Min-Max donusumu

In [17]:
scaler =preprocessing.MinMaxScaler(feature_range =(10,20))


In [19]:
#varyanslari korundu
scaler.fit_transform(df)

array([[10.        , 12.85714286, 11.11111111],
       [13.33333333, 12.85714286, 17.77777778],
       [18.33333333, 10.        , 10.        ],
       [16.66666667, 14.28571429, 11.11111111],
       [20.        , 20.        , 20.        ]])

### Bianrize donusum
## belirli bir degerin altindakilri 0 ustundekilri 1 yap dedigimizde
### veri setinin donusturulmesidir. tasimis oldugu bilgiyi etkiler

In [22]:
binarizer = preprocessing.Binarizer(threshold =5).fit(df)
binarizer.transform(df)

array([[0., 1., 1.],
       [0., 1., 1.],
       [1., 0., 0.],
       [0., 1., 1.],
       [1., 1., 1.]])

#### 0-1 donusumu

In [23]:
## kategoric degisken sayilara degistiriliyor

In [27]:
import seaborn as sns
tips = sns.load_dataset('tips')
df=tips.copy()
df_l =df.copy()

In [28]:
df_l.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [30]:
df_l.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.3 KB


In [31]:
df_l['new_sex']=df_l['sex'].cat.codes
df_l.head()


total_bill   tip     sex smoker  day    time  size  new_sex
0       16.99  1.01  Female     No  Sun  Dinner     2        1
1       10.34  1.66    Male     No  Sun  Dinner     3        0
2       21.01  3.50    Male     No  Sun  Dinner     3        0
3       23.68  3.31    Male     No  Sun  Dinner     2        0
4       24.59  3.61  Female     No  Sun  Dinner     4        1

In [35]:
lbe =preprocessing.LabelEncoder()
df_l['new_new_sex']=lbe.fit_transform(df_l['sex'])


In [36]:
df_l.head()

total_bill   tip     sex smoker  day    time  size  new_sex  new_new_sex
0       16.99  1.01  Female     No  Sun  Dinner     2        1            0
1       10.34  1.66    Male     No  Sun  Dinner     3        0            1
2       21.01  3.50    Male     No  Sun  Dinner     3        0            1
3       23.68  3.31    Male     No  Sun  Dinner     2        0            1
4       24.59  3.61  Female     No  Sun  Dinner     4        1            0

### 1 ve digerleri(0) donusumu

In [37]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [38]:
df_l.head()

total_bill   tip     sex smoker  day    time  size  new_sex  new_new_sex
0       16.99  1.01  Female     No  Sun  Dinner     2        1            0
1       10.34  1.66    Male     No  Sun  Dinner     3        0            1
2       21.01  3.50    Male     No  Sun  Dinner     3        0            1
3       23.68  3.31    Male     No  Sun  Dinner     2        0            1
4       24.59  3.61  Female     No  Sun  Dinner     4        1            0

In [39]:
df_l['new_day']=np.where(df_l['day'].str.contains('Sun'),1,0)

In [41]:
df_l.head()

total_bill   tip     sex smoker  day    time  size  new_sex  new_new_sex  \
0       16.99  1.01  Female     No  Sun  Dinner     2        1            0   
1       10.34  1.66    Male     No  Sun  Dinner     3        0            1   
2       21.01  3.50    Male     No  Sun  Dinner     3        0            1   
3       23.68  3.31    Male     No  Sun  Dinner     2        0            1   
4       24.59  3.61  Female     No  Sun  Dinner     4        1            0   

   new_day  
0        1  
1        1  
2        1  
3        1  
4        1

###  multiple class donusum

In [ ]:
lbe = preprocessing.LabelEncoder()

In [42]:
df_l['daha_yeni_gun']= lbe.fit_transform(df_l['day'])
df_l.head()

total_bill   tip     sex smoker  day    time  size  new_sex  new_new_sex  \
0       16.99  1.01  Female     No  Sun  Dinner     2        1            0   
1       10.34  1.66    Male     No  Sun  Dinner     3        0            1   
2       21.01  3.50    Male     No  Sun  Dinner     3        0            1   
3       23.68  3.31    Male     No  Sun  Dinner     2        0            1   
4       24.59  3.61  Female     No  Sun  Dinner     4        1            0   

   new_day  daha_yeni_gun  
0        1              2  
1        1              2  
2        1              2  
3        1              2  
4        1              2

###  one-hot donusumum ve dumy degisken tuzagi

In [44]:
df_one_hot =df_one_hot= df.copy()

In [45]:
pd.get_dummies(df_one_hot,columns =['sex'],prefix=['sex']).head()

total_bill   tip smoker  day    time  size  sex_Male  sex_Female
0       16.99  1.01     No  Sun  Dinner     2         0           1
1       10.34  1.66     No  Sun  Dinner     3         1           0
2       21.01  3.50     No  Sun  Dinner     3         1           0
3       23.68  3.31     No  Sun  Dinner     2         1           0
4       24.59  3.61     No  Sun  Dinner     4         0           1

In [46]:
pd.get_dummies(df_one_hot,columns =['day'],prefix=['day']).head()

total_bill   tip     sex smoker    time  size  day_Thur  day_Fri  day_Sat  \
0       16.99  1.01  Female     No  Dinner     2         0        0        0   
1       10.34  1.66    Male     No  Dinner     3         0        0        0   
2       21.01  3.50    Male     No  Dinner     3         0        0        0   
3       23.68  3.31    Male     No  Dinner     2         0        0        0   
4       24.59  3.61  Female     No  Dinner     4         0        0        0   

   day_Sun  
0        1  
1        1  
2        1  
3        1  
4        1

### Surekli Degiskeni Kategoric degiskene cevirme

In [47]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [48]:
## kullanacagimiz fonksiyon yapidaki sayisal degiskenleri kendisi ayiramiyoronun yerine biz yapiyoruz
dff=df.select_dtypes(include =['float','int64'])