In [1]:
import numpy as np
import pandas as pd

## Create random dataframe

In [2]:
df = pd.DataFrame({'a':np.random.randint(10,10000,10),'b':np.random.randint(10,10000,10)})
df

a     b
0  6025   488
1  5403  2419
2  3257  3843
3  4773  7781
4   831   890
5  8623  1530
6  8286  5637
7  1354  5055
8  3257  3298
9  4652   287

## Simple manhattan distance between two observation

In [4]:
a=df.iloc[5:6,:]
a

a     b
5  8623  1530

In [5]:
a.values

array([[8623, 1530]])

In [7]:
a.to_numpy()

array([[8623, 1530]])

In [8]:
b=df.iloc[8:9,:]
b.to_numpy()

array([[3257, 3298]])

In [9]:
abs(a-b).sum()

a    0.0
b    0.0
dtype: float64

In [10]:
a=df.iloc[5:6,:].values
b=df.iloc[8:9,:].values
abs(a-b).sum()


7134

In [11]:
a=df.iloc[5:6,:].to_numpy()
b=df.iloc[8:9,:].to_numpy()
abs(a-b).sum()


7134

##  library for getting distance matrix for entire data(euclidean)

In [12]:
from sklearn.metrics import pairwise_distances
X_precomputed = pairwise_distances(df,metric = 'euclidean')
df.head()

a     b
0  6025   488
1  5403  2419
2  3257  3843
3  4773  7781
4   831   890

In [13]:
df_2 = pd.DataFrame(X_precomputed)
df_2

0            1            2            3            4  \
0     0.000000  2028.705252  4349.465369  7399.686007  5209.533568   
1  2028.705252     0.000000  2575.478985  5398.883588  4820.894627   
2  4349.465369  2575.478985     0.000000  4219.727479  3821.738479   
3  7399.686007  5398.883588  4219.727479     0.000000  7938.844059   
4  5209.533568  4820.894627  3821.738479  7938.844059     0.000000   
5  2799.172735  3340.467183  5843.280329  7341.491742  7818.239188   
6  5623.550658  4320.557024  5339.407926  4115.568612  8838.044693   
7  6532.666378  4831.448748  2256.181065  4372.715060  4197.708184   
8  3944.353432  2319.042259   545.000000  4732.393158  3418.177877   
9  1387.634678  2260.403725  3819.837824  7494.976784  3868.287735   

             5            6            7            8            9  
0  2799.172735  5623.550658  6532.666378  3944.353432  1387.634678  
1  3340.467183  4320.557024  4831.448748  2319.042259  2260.403725  
2  5843.280329  5339.407926  2256.181065   545.000000  3819.837824  
3  7341.491742  4115.568612  4372.715060  4732.393158  7494.976784  
4  7818.239188  8838.044693  4197.708184  3418.177877  3868.287735  
5     0.000000  4120.803077  8078.612876  5649.759287  4160.996275  
6  4120.803077     0.000000  6956.389006  5546.328696  6467.492250  
7  8078.612876  6956.389006     0.000000  2590.069111  5797.467378  
8  5649.759287  5546.328696  2590.069111     0.000000  3318.455364  
9  4160.996275  6467.492250  5797.467378  3318.455364     0.000000

## Manhatten matrix

In [14]:
X_precomputed2 = pairwise_distances(df,metric= 'manhattan')
df_3 = pd.DataFrame(X_precomputed2)
df_3

0       1       2        3        4        5        6        7  \
0     0.0  2553.0  6123.0   8545.0   5596.0   3640.0   7410.0   9238.0   
1  2553.0     0.0  3570.0   5992.0   6101.0   4109.0   6101.0   6685.0   
2  6123.0  3570.0     0.0   5454.0   5379.0   7679.0   6823.0   3115.0   
3  8545.0  5992.0  5454.0      0.0  10833.0  10101.0   5657.0   6145.0   
4  5596.0  6101.0  5379.0  10833.0      0.0   8432.0  12202.0   4688.0   
5  3640.0  4109.0  7679.0  10101.0   8432.0      0.0   4444.0  10794.0   
6  7410.0  6101.0  6823.0   5657.0  12202.0   4444.0      0.0   7514.0   
7  9238.0  6685.0  3115.0   6145.0   4688.0  10794.0   7514.0      0.0   
8  5578.0  3025.0   545.0   5999.0   4834.0   7134.0   7368.0   3660.0   
9  1574.0  2883.0  4951.0   7615.0   4424.0   5214.0   8984.0   8066.0   

        8       9  
0  5578.0  1574.0  
1  3025.0  2883.0  
2   545.0  4951.0  
3  5999.0  7615.0  
4  4834.0  4424.0  
5  7134.0  5214.0  
6  7368.0  8984.0  
7  3660.0  8066.0  
8     0.0  4406.0  
9  4406.0     0.0

## https://medium.com/analytics-vidhya/euclidean-and-manhattan-distance-metrics-in-machine-learning-a5942a8c9f2f

## above matrix shows distance from every single sample(observation) against all observations
## yukarıdaki matris, tüm gözlemlere karşı her bir numuneden (gözlem) olan mesafeyi gösterir

## for instance for the pount number 7 the closest observation is row number 4, because they have smallest distance 
## from each other
## örneğin 7 numaralı nokta için en yakın gözlem 4 numaralı satırdır, çünkü birbirlerinden en küçük mesafeye sahiptirler.

In [ ]:
## https://www.analyticsvidhya.com/blog/2020/02/4-types-of-distance-metrics-in-machine-learning/
## https://www.geeksforgeeks.org/sum-manhattan-distances-pairs-points/

### check for missing value

In [16]:
df.isnull()

a      b
0  False  False
1  False  False
2  False  False
3  False  False
4  False  False
5  False  False
6  False  False
7  False  False
8  False  False
9  False  False

In [17]:
df.isnull().any()

a    False
b    False
dtype: bool

## assigning nan values manually

In [35]:
# tum satirlar ama 3 atlaya atlaya..ve birinci sutun
# assign nan values for the column index 1 every after 3 rows
df.iloc[:: 3,1]=np.nan
df

a       b
0  9317     NaN
1   452  8857.0
2   591  9848.0
3  6893     NaN
4  7117  3333.0
5  8981  8634.0
6  1770     NaN
7  9586  8747.0
8  1858  9220.0
9   671     NaN

In [20]:
#df['a']=300

In [21]:
#df

a       b
0  300     NaN
1  300  2419.0
2  300  3843.0
3  300     NaN
4  300   890.0
5  300  1530.0
6  300     NaN
7  300  5055.0
8  300  3298.0
9  300     NaN

In [22]:

##df.loc[0,'a']=0

In [23]:
#df

a       b
0    0     NaN
1  300  2419.0
2  300  3843.0
3  300     NaN
4  300   890.0
5  300  1530.0
6  300     NaN
7  300  5055.0
8  300  3298.0
9  300     NaN

In [24]:
#df.head()

a       b
0    0     NaN
1  300  2419.0
2  300  3843.0
3  300     NaN
4  300   890.0

In [36]:
df.isnull()

a      b
0  False   True
1  False  False
2  False  False
3  False   True
4  False  False
5  False  False
6  False   True
7  False  False
8  False  False
9  False   True

In [37]:
df.isnull().any()

a    False
b     True
dtype: bool

# Handling Missing values

In [38]:
# filling with mean
df.fillna(df['b'].mean(),inplace=True)
df

a       b
0  9317  8106.5
1   452  8857.0
2   591  9848.0
3  6893  8106.5
4  7117  3333.0
5  8981  8634.0
6  1770  8106.5
7  9586  8747.0
8  1858  9220.0
9   671  8106.5

In [39]:
df.fillna(df['b'].median(),inplace =True)
df

a       b
0  9317  8106.5
1   452  8857.0
2   591  9848.0
3  6893  8106.5
4  7117  3333.0
5  8981  8634.0
6  1770  8106.5
7  9586  8747.0
8  1858  9220.0
9   671  8106.5

In [40]:
df.fillna(df['a'].median(),inplace =True)
df

a       b
0  9317  8106.5
1   452  8857.0
2   591  9848.0
3  6893  8106.5
4  7117  3333.0
5  8981  8634.0
6  1770  8106.5
7  9586  8747.0
8  1858  9220.0
9   671  8106.5

In [ ]:
df.fillna(method='ffill')
df.fillna(method ='bfill')