# Mustafa Vahid

# Why numPy

In [2]:
z = [9,8,7,6]
y = [5,4,3,2]

y

[5, 4, 3, 2]

In [3]:
z

[9, 8, 7, 6]

In [5]:
ab =[]
for i in range(0,len(z)):
    ab.append(z[i]*y[i])
ab

[45, 32, 21, 12]

In [6]:
import numpy as np

In [7]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])


In [8]:
a*b

array([ 2,  6, 12, 20])

In [22]:
zy =[]
for i in range(0,len(z)):
    zy.append(z[i])
    zy.append(z[i])
zy

[9, 9, 8, 8, 7, 7, 6, 6]

In [23]:
zy =[]
for i in range(0,len(z)):
    zy.append(z[i]*y[i])
zy

[45, 32, 21, 12]

In [ ]:
import numpy as np

In [ ]:
z_array = np.array(z)

In [ ]:
z_array

In [ ]:
y_array = np.array(y)

In [ ]:
y_array

In [ ]:
#multiplay
z_array*y_array

## Create numPy array

In [24]:
import numpy as np

# create array from list

In [25]:
# create array from list
# numpy array() method
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [26]:
w = np.array([1,2,3,4])
type(w)

numpy.ndarray

In [27]:
# fixed data type  sabit tip baskisi
np.array([3.14,4,2,13])

array([ 3.14,  4.  ,  2.  , 13.  ])

## np.array([3.14,4,2,13,"8"])

In [9]:
t = np.array([3.14,4,2,13],dtype ="float32")
type(t)
print(t)

[ 3.14  4.    2.   13.  ]


### Creating an Array from scratch

In [29]:
np.zeros()

TypeError: zeros() missing required argument 'shape' (pos 1)

In [30]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
np.zeros(10, dtype =int)   # vector 1 dimensional

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [32]:
np.ones((3,5))   # matrix 2D

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [33]:
np.ones((3,5),dtype =int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [34]:
# 3,5 matrix  fill 2
np.full((3,5),2)

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [10]:
# from zero to 31      three by three
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [11]:
  ## create 10 values between zero and one   ## sifir ile bir arasinda 10 tane deger olustur
np.linspace(0,1 ,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [12]:
## with a mean of 10 and a standard deviation of 4/       a matrix of 3 by 4
## ortlamasi 10 standart sapmasi 4 olacak sekilde/  3 e 4 luk bir matrix
np.random.normal(10,4,(3,4))

array([[ 3.56289939,  1.4231152 , 14.65750419,  5.40460045],
       [ 3.14498709, 11.14343557, 12.06576604, 13.03021581],
       [ 6.48068158, 13.87909751, 11.86937203,  8.54322126]])

In [13]:
# I want to generate random data
# rastgele veri olusturmak istiyorum
np.random.randint(0,10,(3,3))

array([[5, 4, 5],
       [5, 0, 6],
       [9, 8, 4]])

In [23]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

## Determint

In [ ]:
detArr = np.random.randint(1,100,25)

In [ ]:
detArr

In [ ]:
np.linalg.det(detArr)

In [ ]:
detArr2 =np.array([[1,2],[3,4]])

In [ ]:
detArr2

In [ ]:
round(np.linalg.det(detArr2))

### numpy array properties
-  **ndim**: _size number_  (boyut sayisi)
* shape: size information(boyut information)
- size: total number of elements(toplam eleman sayisi)
* dtype: array data type (array veri tipi)

In [35]:
import numpy as np

In [36]:
## create array with numpy   /1* 9 vector /1 row  9 column
array =np.array([1,2,3,4,5,6,7,8,9])

In [37]:
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
print(array.shape)

(9,)


In [39]:
import numpy as np

In [6]:
# one dimension array
np.random.randint(10,size =10)   

array([1, 2, 0, 5, 3, 4, 6, 9, 5, 3])

In [7]:
a1= np.random.randint(10,size =10)

In [8]:
a1.ndim

1

In [9]:
# 1 dimension 10 element
a1.shape

(10,)

In [10]:
a1.size

10

In [11]:
#  data type
a1.dtype

dtype('int32')

In [12]:
# 2 dimensional array
b1 =np.random.randint(10,size =(3,5))
b1

array([[0, 7, 9, 7, 6],
       [6, 4, 8, 4, 7],
       [7, 9, 1, 5, 9]])

In [13]:
# dimension
b1.ndim

2

In [14]:
b1.shape

(3, 5)

In [15]:
b1.size

15

In [16]:
b1.dtype

dtype('int32')

## Array indexes

In [ ]:
arr= np.arange(1,10)

In [ ]:
arr

In [ ]:
arr[2]

In [ ]:
arr[5]

In [ ]:
arr[1:5]

In [ ]:
arr[:3]

In [ ]:
arr[:3]=25

In [ ]:
arr

In [24]:
import numpy as np
a = np.random.randint(10, size = 10)
a

array([4, 8, 0, 5, 7, 7, 6, 1, 5, 5])

In [26]:
a[0]

4

In [27]:
a[-1]

5

In [28]:
a [0] =100

In [29]:
a

array([100,   8,   0,   5,   7,   7,   6,   1,   5,   5])

In [ ]:
## 2Dimens Aaray index

In [33]:
import numpy as np
m = np.random.randint(10, size = (3,5))
m

array([[7, 5, 1, 7, 8],
       [9, 9, 8, 8, 3],
       [6, 7, 7, 1, 5]])

In [34]:
m[0,0]

7

In [35]:
m[1,1]

9

In [36]:
m[1,4]

3

In [38]:
m [1,4] =99

In [39]:
m

array([[ 7,  5,  1,  7,  8],
       [ 9,  9,  8,  8, 99],
       [ 6,  7,  7,  1,  5]])

In [40]:
m[1,4]= 2.2

In [41]:
m

array([[7, 5, 1, 7, 8],
       [9, 9, 8, 8, 2],
       [6, 7, 7, 1, 5]])

## Array Alt Kume islemleri(Slicing)

In [42]:
import numpy as np

In [43]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

## What does slice mean? It is the expression that we say go from here to there. :  expressed with colon
## slice ne demek  ? suradan suraya git  dedigimiz ifadedir.: ile gosterilir


In [44]:
# o dan 3 e kadar git
a[0:3]

array([20, 21, 22])

In [45]:
a[:3]

array([20, 21, 22])

In [46]:
# 3 den sona kadar git
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [47]:
# 1. elemandan basla 2 iki git
a[1::2]

array([21, 23, 25, 27, 29])

## iki boyutlu slice islemleri

In [49]:
m =np.random.randint(10,size =(5,5))
m

array([[9, 7, 5, 4, 8],
       [8, 6, 3, 9, 1],
       [8, 8, 2, 3, 6],
       [9, 3, 1, 1, 6],
       [2, 3, 4, 4, 8]])

In [ ]:
# matris iki bilesenden olusur.satirlar ve sutunlar

In [50]:
# tum satirlar  ve ilk sutun.  sutuna erismek icin tum satiri secmek zorundayim.
m[:,0]

array([9, 8, 8, 9, 2])

In [51]:
m[:,1]

array([7, 6, 8, 3, 3])

In [53]:
m

array([[9, 7, 5, 4, 8],
       [8, 6, 3, 9, 1],
       [8, 8, 2, 3, 6],
       [9, 3, 1, 1, 6],
       [2, 3, 4, 4, 8]])

In [52]:
# satir sececegim    o. satir tum sutunlar
m[0,:]

array([9, 7, 5, 4, 8])

In [54]:
m[0]

array([9, 7, 5, 4, 8])

In [55]:
m[1,:]

array([8, 6, 3, 9, 1])

In [57]:
m[1]

array([8, 6, 3, 9, 1])

In [58]:
# hem satirlara hem sutunlara erisip belirli elemanlari secmek isteyelim
# o dan 2 ye kadar satirlari /0 dan 3 e kadar sutnlari al
m[0:2,0:3]

array([[9, 7, 5],
       [8, 6, 3]])

In [59]:
m

array([[9, 7, 5, 4, 8],
       [8, 6, 3, 9, 1],
       [8, 8, 2, 3, 6],
       [9, 3, 1, 1, 6],
       [2, 3, 4, 4, 8]])

In [60]:
# tum satirlari al  iki sutunu
m[::,:2]

array([[9, 7],
       [8, 6],
       [8, 8],
       [9, 3],
       [2, 3]])

In [61]:
m[1:3,0:2]

array([[8, 6],
       [8, 8]])

##  Alt kume uzerinde islem yapmak

In [19]:
import numpy as np
a =np.random.randint(10,size =(5,5))
a

array([[7, 8, 2, 9, 6],
       [6, 4, 8, 2, 2],
       [8, 0, 7, 9, 2],
       [8, 0, 9, 0, 5],
       [3, 0, 5, 5, 5]])

## alt kume uzerinde islem yaparken  ana kume yi etkilemesini istemiyorum. Bunu nasil halledebilirim?
## I don't want it to affect the main cluster when operating on the subset. How can I handle this?

In [20]:
down_a =a[0:3,0:2]
down_a

array([[7, 8],
       [6, 4],
       [8, 0]])

In [21]:
a

array([[7, 8, 2, 9, 6],
       [6, 4, 8, 2, 2],
       [8, 0, 7, 9, 2],
       [8, 0, 9, 0, 5],
       [3, 0, 5, 5, 5]])

In [22]:
down_a[0,0] =999
down_a[1,1] =888

In [23]:
down_a

array([[999,   8],
       [  6, 888],
       [  8,   0]])

In [24]:
## There has been a change in the main structure.but I don't want

a

array([[999,   8,   2,   9,   6],
       [  6, 888,   8,   2,   2],
       [  8,   0,   7,   9,   2],
       [  8,   0,   9,   0,   5],
       [  3,   0,   5,   5,   5]])

In [ ]:
## I will use a method named copy for this

In [25]:
import numpy as np
b =np.random.randint(10,size =(5,5))
b

array([[5, 4, 9, 7, 0],
       [5, 1, 5, 4, 7],
       [2, 3, 3, 8, 1],
       [2, 2, 7, 1, 9],
       [1, 3, 6, 2, 0]])

In [28]:
## makes it independent from the main array.
down_b =b[0:3,0:2].copy()
down_b

array([[5, 4],
       [5, 1],
       [2, 3]])

In [32]:
 
down_b[0,0]=999
down_b[0,1]=888
down_b

array([[999, 888],
       [  5,   1],
       [  2,   3]])

In [33]:
# The change I made to the subset no longer affects the main array structure

In [34]:
b

array([[5, 4, 9, 7, 0],
       [5, 1, 5, 4, 7],
       [2, 3, 3, 8, 1],
       [2, 2, 7, 1, 9],
       [1, 3, 6, 2, 0]])

## Accessing elements with Fancy index
## Fancy  index ile Elemanlara Erismek

## Important for our

In [35]:
import numpy as np
v =np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [36]:
v[1]

3

In [37]:
v[3]

9

In [38]:
v[5]

15

In [39]:
## if we want to reach all of them at the same time
[v[1],v[3],v[5]]

[3, 9, 15]

In [45]:
fetch =[1,3,5]
fetch

[1, 3, 5]

In [43]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [44]:
v[fetch]

array([ 3,  9, 15])

### fancy index in two dimensions

In [46]:
m =np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [48]:
row = np.array([0,1])
column = np.array([1,2])


In [49]:
m[row,column]

array([1, 5])

## simple index and fancy index

In [50]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [51]:
m[0,[1,2]]

array([1, 2])

##  slice

In [52]:
m[0 : ,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [53]:
m[0 : -1,[1,2]]

array([[1, 2],
       [4, 5]])

## conditional element operations

In [54]:
import numpy as np
v =np.array([1,2,3,4,5])
# on a vector basis

In [55]:
v>5 

array([False, False, False, False, False])

In [56]:
v<3

array([ True,  True, False, False, False])

In [59]:
v [v<3]

array([1, 2])

In [64]:
v [v <= 3]

array([1, 2, 3])

In [62]:
v [v>=3]

array([3, 4, 5])

In [65]:
v [v==3]

array([3])

In [68]:
v [v != 3]

array([1, 2, 4, 5])

In [69]:
v

array([1, 2, 3, 4, 5])

In [70]:
v*2

array([ 2,  4,  6,  8, 10])

In [71]:
v/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [72]:
v*5/10

array([0.5, 1. , 1.5, 2. , 2.5])

In [73]:
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)

## Aritmetic Operators

## ufunc

In [74]:
np.subtract(v,1)

array([0, 1, 2, 3, 4])

In [75]:
np.add(v,1)

array([2, 3, 4, 5, 6])

In [77]:
np.multiply(v,3)

array([ 3,  6,  9, 12, 15])

In [79]:
np.divide(v,3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [81]:
np.power(v,3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [82]:
v%2

array([1, 0, 1, 0, 1], dtype=int32)

In [83]:
np.mod(v,2)

array([1, 0, 1, 0, 1], dtype=int32)

In [85]:
## mutlak deger
np.absolute(np.array([-3]))

array([3])

## Equation with two unknowns with numpy

In [87]:
# linear algebra library
import numpy as np

###  5*x0 +x1 =12
###  x0 +3*x1 =10

In [90]:
# katsayilar(coeffifient)
a =np.array([[5,1],[1,3]])
b =np.array([12,10])

In [91]:
a

array([[5, 1],
       [1, 3]])

In [92]:
b

array([12, 10])

In [93]:
x =np.linalg.solve(a,b)

In [94]:
x

array([1.85714286, 2.71428571])

# Datai Team

In [40]:
## create matrix
a = array.reshape(3,3)


In [41]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
a.shape

(3, 3)

In [43]:
print(a.shape)

(3, 3)


In [44]:
## dimension    name.ndim
print(a.ndim)

2


In [45]:
type(a)

numpy.ndarray

In [46]:
## type
print("data type",a.dtype.name)

data type int32


In [47]:
print("size:",a.size)

size: 9


In [ ]:
## reshape kullanmadan matrix olusturmak
array_1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [ ]:
array_1

### Allocate Zeros

In [48]:
## allocate
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [49]:
zeros = np.zeros((3,4))

In [50]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [51]:
zeros[0,0]=5
zeros[0,1]=5
zeros[0,2]=5
zeros[0,3]=5

In [52]:
zeros

array([[5., 5., 5., 5.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [53]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [54]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

### Arange()  verilen iki sayi arasini  beser beser say

In [55]:
a=np.arange(10,50,5)

In [56]:
a

array([10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
## verilen iki sayi arasinda 20 tane sayi olsun
a =np.linspace(10,50,20)

In [ ]:
a

## Numpy Basic Operations

In [57]:
## 
a =np.array([1,2,3])

In [58]:
b =np.array([4,5,6])

In [59]:
a+b

array([5, 7, 9])

In [60]:
print(a-b)

[-3 -3 -3]


In [61]:
a*b

array([ 4, 10, 18])

In [62]:
print(a/b)

[0.25 0.4  0.5 ]


In [63]:
a**b

array([  1,  32, 729], dtype=int32)

In [64]:
print(a**b)

[  1  32 729]


In [65]:
print(np.sin(a))

[0.84147098 0.90929743 0.14112001]


In [66]:
print(a<2)

[ True False False]


In [67]:
a =np.array([[1,2,3],[4,5,6]])
b =np.array([[1,2,3],[4,5,6]])

In [68]:
# element wise prodcut
print(a*b)

[[ 1  4  9]
 [16 25 36]]


In [69]:
# matrix prodcut   Tranzpoz
a.dot(b.T)

array([[14, 32],
       [32, 77]])

In [70]:
print(np.exp(a))

[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]


In [71]:
## 0 ile 1 arasi
a =np.random.random((5,5))

In [72]:
a

array([[0.75931269, 0.70158698, 0.12096278, 0.29123306, 0.17487578],
       [0.98966167, 0.43368946, 0.36011415, 0.72160783, 0.05812763],
       [0.53900164, 0.91464141, 0.79918118, 0.53123052, 0.5333037 ],
       [0.84328241, 0.82029548, 0.92372657, 0.88530738, 0.41562813],
       [0.2258027 , 0.3084225 , 0.0984131 , 0.12810314, 0.79250882]])

In [ ]:
print(a.sum())

In [ ]:
print(a.max())

In [ ]:
print(a.min())

In [74]:
# matrix teki satir ve sutunlari toplamak
# columnlari toplamak
print(a.sum(axis=0))

[3.35706111 3.17863584 2.30239778 2.55748193 1.97444406]


In [73]:
## sum of rows
print(a.sum(axis = 1))

[2.04797129 2.56320075 3.31735845 3.88823998 1.55325025]


In [75]:
print(np.sqrt(a))

[[0.8713855  0.83760789 0.34779704 0.53966013 0.41818151]
 [0.99481741 0.65855103 0.60009512 0.84947503 0.24109673]
 [0.73416731 0.95636887 0.89396934 0.72885562 0.73027645]
 [0.9183041  0.90570165 0.96110695 0.94090774 0.64469227]
 [0.47518701 0.55535799 0.31370862 0.35791499 0.89022964]]


In [76]:
print(np.square(a))  ##  a**2

[[0.57655576 0.49222429 0.014632   0.08481669 0.03058154]
 [0.97943022 0.18808655 0.1296822  0.52071787 0.00337882]
 [0.29052277 0.83656891 0.63869057 0.28220586 0.28441283]
 [0.71112523 0.67288468 0.85327077 0.78376916 0.17274674]
 [0.05098686 0.09512444 0.00968514 0.01641041 0.62807023]]


In [77]:
np.add(a,a)

array([[1.51862538, 1.40317396, 0.24192557, 0.58246611, 0.34975156],
       [1.97932334, 0.86737892, 0.7202283 , 1.44321567, 0.11625526],
       [1.07800328, 1.82928282, 1.59836237, 1.06246104, 1.0666074 ],
       [1.68656483, 1.64059097, 1.84745314, 1.77061476, 0.83125625],
       [0.4516054 , 0.616845  , 0.1968262 , 0.25620628, 1.58501764]])

## Indexing and Slicing

In [112]:
array = np.array([1,2,3,4,5,6,7])  # vector   dimension 1

In [113]:
print(array[0])

1


In [114]:
print(array[3])

4


In [115]:
print(array[6])

7


In [116]:
print(array[7])

IndexError: index 7 is out of bounds for axis 0 with size 7

In [117]:
print(array[:4])

[1 2 3 4]


In [118]:
print(array[:4])

[1 2 3 4]


## Reverse

In [124]:
reverse_array =array[:-1]

In [125]:
print(reverse_array)

[1 2 3 4 5 6]


In [128]:
## two dimensional array

d2_array = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [129]:
print(d2_array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [130]:
# 0.row 4.column
d2_array[0][4]

5

In [131]:
print(d2_array[1,1])

7


In [132]:
# all rows  one column
d2_array[:,1]

array([2, 7])

In [ ]:
## 1.row and 1,2,3 column
print(d2_array[1, 1:4])

In [133]:
print(d2_array[-1])

[ 6  7  8  9 10]


In [134]:
# last value and   all column
print(d2_array[-1,:])

[ 6  7  8  9 10]


In [135]:
# tum satirlar daki son sutunlar  last columns on all raws
print(d2_array[:,-1])

[ 5 10]


## shape manipulation

In [14]:
array =np.array([[1,2,3],[4,5,6],[7,8,9]])

In [15]:
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

###  manipulate matrix to vector  flatten

In [17]:
## manipulate matrix to vector  flatten
a = array.ravel()

In [18]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
list1 = [1,2,3]
list2 = [4,5,6]
list3 = [7,8,9]

In [20]:
array1 = np.concatenate([list1 , list2,list3])

In [21]:
a1 = array1.ravel()

In [22]:
a1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

##  Reshape()
###  Yeniden sekillendirme

* Datai Team
- Mustafa vahit

In [ ]:
np.arange (1,10)

In [ ]:
np.arange (1,10).reshape(3,3)

In [ ]:
c1 =np.arange (1,10)

In [ ]:
# single square bracket   /tek koseli parantz
c1

In [ ]:
c1.ndim

In [ ]:
 # two square bracket  /iki koseli parantez
c1.reshape((1,9))

In [ ]:
c2 =c1.reshape((1,9))
c2

In [ ]:
c2.ndim

In [ ]:
# DATAI TEAM

In [ ]:
array2= a.reshape(3,3)

In [ ]:
print(array2)

In [ ]:
## Transpoz     satiri sutun sutunu satir yapmak
array_Transpoz = array2.T

In [ ]:
array_Transpoz

In [ ]:
print(array_Transpoz.shape)

### Resize

In [ ]:
array5 =np.array([[1,2],[3,4],[5,6]])

In [ ]:
array5

In [ ]:
array5.reshape(2,3)

In [ ]:
array5.resize((2,3))

In [ ]:
array5

### different between reshape() and resize() methods

### Concatenation(Birlestirme)

In [97]:
k =np.array([1,2,3])
l =np.array([4,5,6])

In [98]:
np.concatenate([k,l])

array([1, 2, 3, 4, 5, 6])

In [99]:
j =np.array([7,8,9])

In [100]:
np.concatenate([k,l,j])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
# 2Dimension

In [102]:
d2_arr =np.array([[1,2,3],[4,5,6]])
d2_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [103]:
np.concatenate([d2_arr,d2_arr])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [104]:
# axis = 0  row
np.concatenate([d2_arr,d2_arr],axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [105]:
# axis = 1  column
np.concatenate([d2_arr,d2_arr],axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

### Stacking array /  araylari birlestirme

In [106]:
array_6= np.array([[1,2],[3,4]])
array_7= np.array([[-1,-2],[-3,-4]])

In [107]:
print(array_6)
print(array_7)

[[1 2]
 [3 4]]
[[-1 -2]
 [-3 -4]]


### Vertical birlestirme

In [108]:
arr_vert_stacking =np.vstack((array_6,array_7))

In [109]:
print(arr_vert_stacking)

[[ 1  2]
 [ 3  4]
 [-1 -2]
 [-3 -4]]


### Horizontal birlestirme

In [110]:
arr_vert_stacking1 =np.hstack((array_6,array_7))

In [111]:
print(arr_vert_stacking1)

[[ 1  2 -1 -2]
 [ 3  4 -3 -4]]


## Convert and Copy Array

In [ ]:
## list
list1 =[1,2,3,4]

In [ ]:
## listeden arraye gecmek  np.array
array = np.array(list1)

In [ ]:
array

In [ ]:
## Array den  listeye donmek

list2 = list(array)

### Copy

In [ ]:
m = np.array([1,2,3])

In [ ]:
n=m

In [ ]:
o =m

In [ ]:
m

In [ ]:
n

In [ ]:
o

In [ ]:
n [0] =5

In [ ]:
m

In [ ]:
n

In [ ]:
o

In [ ]:
## solve
p = np.array([1,2,3])

In [ ]:
r =p.copy()

In [ ]:
s = p.copy()

In [ ]:
s [0] =5

In [ ]:
s

In [ ]:
r

### Splitting (Array ayirma)

#### Mustafa Vahit

In [84]:
f_arr =np.array([1,2,3,99,99,3,2,1])

In [85]:
np.split(f_arr,[3,5,])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [86]:
f1,f2,f3 = np.split(f_arr,[3,5])

In [87]:
f1

array([1, 2, 3])

In [88]:
f2

array([99, 99])

In [89]:
f3

array([3, 2, 1])

In [90]:
# 2D split

In [91]:
twoDim =np.arange(16).reshape(4,4)
twoDim

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [92]:
np.vsplit(twoDim,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [93]:
up,down =np.vsplit(twoDim, [2])

In [94]:
up

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [95]:
down

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [96]:
twoDim

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.hsplit(twoDim,[2])

In [ ]:
right,left = np.hsplit(twoDim,[2]) 

In [ ]:
right

In [ ]:
left

##### sorting

In [1]:
import numpy as np

In [2]:
v = np.array([2,1,4,3,5])

In [3]:
## vector
v

array([2, 1, 4, 3, 5])

In [4]:
#sort
np.sort(v)

array([1, 2, 3, 4, 5])

In [5]:
v.sort()

In [ ]:
## sort metodu numpy in icerisinden cagrilirsa orjinal veriyi bozmaz.ama name.sort()olarak 
## cagirirsak yapiyi tamamen degistirir

In [ ]:
#2D array sort

In [8]:
#ortalama 20  standart sapma 5
m= np.random.normal(20,5,(3,3))

In [9]:
m

array([[17.13325782, 16.33256962, 21.20108551],
       [23.28323353, 25.04415199, 27.04782667],
       [15.28021333, 19.26442211, 23.39216739]])

In [10]:
# her bir satiri kucukten buyuge dogru siralamis
np.sort(m, axis =1)

array([[16.33256962, 17.13325782, 21.20108551],
       [23.28323353, 25.04415199, 27.04782667],
       [15.28021333, 19.26442211, 23.39216739]])

In [11]:
# sutunlara gore kucukten buyuge dogru
np.sort(m,axis =0)

array([[15.28021333, 16.33256962, 21.20108551],
       [17.13325782, 19.26442211, 23.39216739],
       [23.28323353, 25.04415199, 27.04782667]])

## Multidemensional array and seperate

In [2]:
import numpy as np
newArray=np.arange(1,21)

In [3]:
newArray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [7]:
newArray = newArray.reshape(5,4)

In [8]:
newArray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [9]:
newArray[0,0]

1

In [10]:
newArray[:,:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18]])

In [11]:
newArray[:3,:3]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [12]:
arr =np.arange(1,11)

In [13]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arr>3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [15]:
booleanArray =arr>3

In [16]:
arr[booleanArray]

array([ 4,  5,  6,  7,  8,  9, 10])

In [17]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])